CREATE DATABASE client;
USE client;
CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) PRIMARY KEY CHECK (CLIENTNO LIKE 'C%'),
    NAME VARCHAR(20) NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE INTEGER CHECK (PINCODE >= 0),
    STATE VARCHAR(15),
    BALDUE DECIMAL(10, 2) DEFAULT 0.00
  CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO VARCHAR(6),
    CHECK (PRODUCTNO LIKE 'P%'),
    DESCRIPTION VARCHAR(15) NOT NULL,
    PROFITPERCENT DECIMAL(4,2) NOT NULL,
    UNIT_MEASURE VARCHAR(10) NOT NULL,
    QTYONHAND INTEGER(8) NOT NULL,
    REORDERLVL INTEGER(8) NOT NULL,
    SELLPRICE DECIMAL(8,2) NOT NULL,
    COSTPRICE DECIMAL(8,2) NOT NULL
);
CREATE TABLE SALESMAN_MASTER (
    SALESMANNO VARCHAR(6) PRIMARY KEY CHECK (SALESMANNO LIKE 'S%'),
    SALESMANNAME VARCHAR(20) NOT NULL,
    ADDRESS1 VARCHAR(30) NOT NULL,
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE INTEGER(8),
    STATE VARCHAR(20),
    SALAMT REAL(8,2) NOT NULL CHECK (SALAMT <> 0),
    TGTTOGET DECIMAL(6,2) NOT NULL CHECK (TGTTOGET <> 0),
    YTDSALES DOUBLE(6,2) NOT NULL,
    REMARKS VARCHAR(60)
  INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES
    -> ('C00001', 'Ivan bayross', 'Mumbai', 400054, 'Maharashtra', 15.000),
    -> ('C00002', 'Mamta muzumdar', 'Madras', 780001, 'Tamil Nadu', 0.0),
    -> ('C00003', 'Chhaya bankar', 'Mumbai', 400057, 'Maharashtra', 50.00),
    -> ('C00004', 'Ashwini joshi', 'Bangalore', 560001, 'Karnataka', 0.0),
    -> ('C00005', 'Hansel colaco', 'Mumbai', 400060, 'Maharashtra', 200.0),
    -> ('C00006', 'Deepak sharma', 'Mangalore', 560050, 'Karnataka', 0.0)
  SELECT * FROM CLIENT_MASTER;
INSERT INTO SALESMAN_MASTER (SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE, STATE, SALAMT, TGTTOGET, YTDSALES) VALUES
    -> ('S00001', 'Aman', 'A/41', 'Worli', 'Mumbai', 400002, 'Maharashtra', 8, 5, 5),
    -> ('S00002', 'Mohit', 'G5', 'Jain', 'Mumbai', 400057, 'Maharashtra', 7, 5, 5),
    -> ('S00003', 'Raj', 'P/5', 'Bandra', 'Mumbai', 400032, 'Maharashtra', 9, 5, 5),
    -> ('S00004', 'Juhu', 'Juhu', 'Mumbai', 400004, 'Maharashtra', 6, 5, 5);
SELECT * FROM PRODUCT_MASTER
SELECT NAME FROM CLIENT_MASTER
SELECT * FROM CLIENT_MASTER
  SELECT NAME, CITY, STATE FROM CLIENT_MASTER
SELECT DESCRIPTION FROM PRODUCT_MASTER;
SELECT * FROM CLIENT_MASTER WHERE CITY = 'Mumbai';
SELECT SALESMANNAME FROM SALESMAN_MASTER WHERE SALAMT = 3000;
UPDATE CLIENT_MASTER SET BALDUE 1000 WHERE CLIEΝΤΝΟ 'C00001';
UPDATE PRODUCT_MASTER SET COSTPRICE 950 WHERE PRODUCTNO = P07868';
